# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "default"
defaultContentLanguage = "en"

# Hugo settings
disableHugoGeneratorInject = true
disableKinds = ["rss", "section", "sitemap", "taxonomy", "term"]
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGoogleAnalytics = true

[languages]
  [languages.en]
    title = "Puig & Co."
    languageCode = "en"
    [languages.en.params]
      description = "Providing AWS consulting and professional services."
