name: Next.js Static Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      NEXT_TELEMETRY_DISABLED: '1'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --check-files --ignore-scripts

      - name: Build static website
        run: |
          yarn lint && yarn build && yarn export

      - uses: actions/cache@v3
        with:
          path: out
          key: nextjs-${{ github.sha }}-${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/cache@v3
        id: build-cache
        with:
          path: out
          key: nextjs-${{ github.sha }}-${{ github.run_number }}

      - name: Configure gh-pages
        run: |
          echo ${{ github.event.repository.name }} > out/CNAME
          mv out/404/index.html out/404.html

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' && steps.build-cache.outputs.cache-hit == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./out
